title: Ethan Linck
description: Ph.D. Candidate, UW Biology
show_downloads: true
google_analytics:
theme: 
pages_list:       
  Home: '/index'
  CV: '/cv'
  Research: '/research'
  Running: '/running'