title: Ethan Linck
description: Postdoctoral Research Associate, University of Tennessee
show_downloads: true
google_analytics: UA-98690382-1
permalink: /:categories/:year-:month-:day-:title.html
pages_list:       
  Home: '/index'
  CV: '/cv'
  Research: '/research'
  Running: '/running'
  News: '/blog'
  Gallery: '/photos'
gems:
  - jekyll-feed