title: Ethan Linck
description: Ph.D. Candidate, UW Biology
show_downloads: true
google_analytics: UA-98690382-1
pages_list:       
  Home: '/index'
  CV: '/cv'
  Research: '/research'
  Running: '/running'
  Blog: '/blog'