title: Ethan Linck
description: Ph.D. Candidate, UW Biology
show_downloads: true
google_analytics: UA-98690382-1
permalink: /:categories/:year-:month-:day-:title.html
pages_list:       
  Home: '/index'
  CV: '/cv'
  Research: '/research'
  Running: '/running'
  Gallery: '/photos'
  Blog: '/blog'
gems:
  - jekyll-feed